### ISSUE TITLE
Setting `edge` on cdevV2 GPIO raises an OSError 22 of "Invalid Argument"

### ISSUE THREAD

**Issue by RobertDeRose** [vsergeev/python-periphery#70]
```python
>>> input = pp.GPIO("/dev/gpiochip3", 10, "in", inverted=True, drive="default")

>>> input.edge="falling"
Traceback (most recent call last):
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 269, in _reopen
    fcntl.ioctl(self._chip_fd, Cdev2GPIO._GPIO_V2_GET_LINE_IOCTL, line_request)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 525, in _set_edge
    self._reopen(self._direction, edge, self._bias, self._drive, self._inverted)
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 271, in _reopen
    raise GPIOError(e.errno, "Opening input line handle: " + e.strerror)
periphery.gpio.GPIOError: [Errno 22] Opening input line handle: Invalid argument


>>> input.edge="rising"
Traceback (most recent call last):
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 269, in _reopen
    fcntl.ioctl(self._chip_fd, Cdev2GPIO._GPIO_V2_GET_LINE_IOCTL, line_request)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 525, in _set_edge
    self._reopen(self._direction, edge, self._bias, self._drive, self._inverted)
  File "/root/gpio_controller/.venv/lib/python3.10/site-packages/periphery/gpio_cdev2.py", line 271, in _reopen
    raise GPIOError(e.errno, "Opening input line handle: " + e.strerror)
periphery.gpio.GPIOError: [Errno 22] Opening input line handle: Invalid argument

>>> input.__class__.__name__
'Cdev2GPIO'
```

OS: Linux rock-3b 5.10.160-legacy-rock-3b #1 SMP Thu Feb 29 08:50:21 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
Installed version: python-periphery   2.4.1

Because of this issue, poll and read_event do not work

**Comment by vsergeev** [comment]
I took a look at GPIO controller driver in the kernel from your version and I can't find an obvious reason for the EINVAL. If you are still using the platform, could you try it with 1) `input.edge="both"`, and 2) with a newer kernel?

**Comment by theshaun** [comment]
Confirming I can replicate this on Linux femtofox 5.10.160 #1 Wed Jan 21 20:37:24 AEST 2026 armv7l armv7l armv7l GNU/Linux

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/periphery/gpio_cdev2.py", line 269, in _reopen
    fcntl.ioctl(self._chip_fd, Cdev2GPIO._GPIO_V2_GET_LINE_IOCTL, line_request)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pymc_repeater/test_ieq.py", line 5, in <module>
    gpio = GPIO("/dev/gpiochip1", 23, "in", edge="both")  # CdevGPIO still works if line is active
  File "/usr/local/lib/python3.10/dist-packages/periphery/gpio_cdev2.py", line 173, in __init__
    self._open(path, line, direction, edge, bias, drive, inverted, label)
  File "/usr/local/lib/python3.10/dist-packages/periphery/gpio_cdev2.py", line 224, in _open
    self._reopen(direction, edge, bias, drive, inverted)
  File "/usr/local/lib/python3.10/dist-packages/periphery/gpio_cdev2.py", line 271, in _reopen
    raise GPIOError(e.errno, "Opening input line handle: " + e.strerror)
periphery.gpio.GPIOError: [Errno 22] Opening input line handle: Invalid argument
```

I am wondering if its an issue with linux 5.10.160 on the rockchips

**Comment by theshaun** [comment]
Confirmed its kernel issue. if you don't need realtime timestamps, the following should work

> 
> import periphery.gpio_cdev2 as _cdev
> _cdev.Cdev2GPIO._GPIO_V2_LINE_FLAG_EVENT_CLOCK_REALTIME = 0
> 

seems support was added in about kernel 5.16
